### PR TITLE
Initial integration with pretix

### PR DESCRIPTION
**Pull request by patrick91**
### TODO:

- [x] configure correct event
- [ ] styling (in another PR maybe)
- [x] send user data
- [x] ask users to login?

### Questions

This seems cool, but I have a few questions:

1. How do we map users to tickets? Shall we use a custom "question" and add the user ID?
2. How can change the link that's shown when paying for the ticket? currently it links to pretix, we'd like to show all the tickets on our site.
3. Do we force the users to be logged in to get tickets? 
4. ...

### CODE REVIEW

**Comment by marcoacierno** [comment]
What is the current status of the PR? I can continue with the integration if that's cool for you

**Comment by patrick91** [comment]
@marcoacierno if you want you can take it, I can focus on the CFP

**Comment by marcoacierno** [comment]
>  configure correct event

done, I added a field "pretix event url" (not required)

**Comment by marcoacierno** [comment]
Closed as we have the new design tickets page PR: #1262

**Pull request closed without merging**
